# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b55fb7157a1bf45a72026c8957f3f68f7c5ac9fa0ec82a4fb996dcc61cb4d28ccd5afd35bc0cc85abc2dfa84d628f84b56fe97a11af98ab67dd597994a82862f

test:
  secret_key_base: 897b2c72e3da6ef7b3887409c79641ffb973e90a3dee5fa644f77244bb9f6d71ff5ed307ba64a7f2a81949e43f047fd3fad3e165f0e646d6f70493639145b7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
